FROM node:13.12.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV HTTPS=true
ENV SSL_CRT_FILE=~/reactcert/61619066_silverstream.dy.fi3000.cert
ENV SSL_KEY_FILE=~/reactcert/61619066_silverstream.dy.fi3000.key


# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

COPY . ./

EXPOSE 3000

# start app
CMD ["npm", "start"]